set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {prl_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports rx_channel]
set_property IOSTANDARD LVCMOS33 [get_ports tx_channel]
set_property IOSTANDARD LVCMOS33 [get_ports wr_en]

set_property PACKAGE_PIN V2 [get_ports {inp_data[0]}]
set_property PACKAGE_PIN U2 [get_ports {inp_data[1]}]
set_property PACKAGE_PIN U1 [get_ports {inp_data[2]}]
set_property PACKAGE_PIN T2 [get_ports {inp_data[3]}]
set_property PACKAGE_PIN T1 [get_ports {inp_data[4]}]
set_property PACKAGE_PIN R2 [get_ports {inp_data[5]}]
set_property PACKAGE_PIN R1 [get_ports {inp_data[6]}]
set_property PACKAGE_PIN P2 [get_ports {inp_data[7]}]
set_property PACKAGE_PIN G1 [get_ports {prl_data[0]}]
set_property PACKAGE_PIN G2 [get_ports {prl_data[1]}]
set_property PACKAGE_PIN F1 [get_ports {prl_data[2]}]
set_property PACKAGE_PIN F2 [get_ports {prl_data[3]}]
set_property PACKAGE_PIN E1 [get_ports {prl_data[4]}]
set_property PACKAGE_PIN E2 [get_ports {prl_data[5]}]
set_property PACKAGE_PIN E3 [get_ports {prl_data[6]}]
set_property PACKAGE_PIN E5 [get_ports {prl_data[7]}]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property PACKAGE_PIN J5 [get_ports reset]

set_property PACKAGE_PIN J1 [get_ports wr_en]
set_property PACKAGE_PIN N5 [get_ports tx_channel]
set_property PACKAGE_PIN N4 [get_ports rx_channel]

set_property IOSTANDARD LVCMOS33 [get_ports rx_done]
set_property PACKAGE_PIN V3 [get_ports rx_done]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
